version: 2

sources:
  - name: raw_data
    description: "Raw data sources for NYC taxi rides"
    database: data-warehousing-486717
    schema: nytaxi
    tables:
      - name: yellow_tripdata
      - name: green_tripdata
